name: Maven Build and Auto-Merge Workflow

on:
  workflow_dispatch:
    inputs:
      buildVersion:
        description: 'SNAPSHOT Build Version'
        required: true

jobs:
  update-pom-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Update POM.xml with SNAPSHOT version
        run: |
          sed -i '/<name>swagger-petstore<\/name>/{n;s|<version>.*</version>|<version>${{ github.event.inputs.buildVersion }}</version>|}' pom.xml
      
      
      - name: Build with Maven
        run: mvn clean install

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "Update SNAPSHOT version to ${{ github.event.inputs.buildVersion }}" || echo "No changes to commit"
          git push origin main
      
      